### ISSUE TITLE
getting current screen index / horizontal scrolling

### ISSUE THREAD

**Issue by skeddles** [TheOathMan/Godot-Android-Live-Wallpaper#2]
In android you can usually add multiple home screens to organize your icons onto, and swipe horizontally between them. Most versions allow you to set a static wallpaper that scrolls slightly with a parallax effect as you scroll between them.

example:
![EAcsX](https://github.com/user-attachments/assets/0d24433a-f397-43ac-b685-36ea15ccb53e)

Is there any way to get the current scroll position of the home screen, or the current screen, so I can emulate that effect with this plugin?

I took a look at your signals and static functions, but didn't see anything that seemed related. If it's not currently possible, then consider this a feature request 

Anyway thanks for making this, seems like a great plugin, and everything else seems to be working!

**Comment by TheOathMan** [comment]
The plugin has an offset callback but was not implemented yet. Every time you scroll the home screen, the wallpaper plugin sends X and Y offset values range from 0.0 to 1.0, representing the current position of the home screen relative to the available space. It also sends other useful values for pixel perfect positioning.

I will implement it soon. It should be fairly straightforward implementation.  

Thank you for letting me know you need this. Good luck.

**Comment by skeddles** [comment]
Thanks! Looking forward to it! I will make a parallax wallpaper with it as soon as it's implemented!

**Comment by TheOathMan** [comment]
> Thanks! Looking forward to it! I will make a parallax wallpaper with it as soon as it's implemented! 

Check out the new on_offset_changed signal. It should do what you want. Both a new release and a repo update have been uploaded.

**Comment by skeddles** [comment]
I tried it out but unfortunately could not get it working. 

I deleted the livewallpaper addon folder and used the one from the releases tab, and restarted.
I found the signal on the LiveWallpaper node and connected it, but it doesn't seem to be firing when I scroll my screen (my positions aren't changing and it's not showing in the log)

maybe I installed/used it wrong? I hope my phone isn't too old (android 11)

```
func _on_live_wallpaper_on_offsets_changed(Offset, OffsetStep, PixelOffset):
	consolelog('offset')
	$moveme.offset.x = (Offset.x-0.5) * 100
	$moveme2.offset.x = PixelOffset.x
```

my project: [LospecWallpaperShoppe.zip](https://github.com/user-attachments/files/16591700/LospecWallpaperShoppe.zip)
video: https://drive.google.com/file/d/1kGyWCXPbTb_ogBjbMXOde6aNA6BIhlcC/view?usp=sharing

**Comment by TheOathMan** [comment]
It's a Godot issue. For some reason, in Godot 4.2.2.stable, the Engine can not register on_offset_changed signal, but when I tried your project in Godot 4.3.beta3, everything seems to be working. The little character moves as you scroll.
I will investigate further and see what I can do.

**Comment by TheOathMan** [comment]
I found the Issue, Godot 4.2 can not handle 6 parameters for the signal coming from the android native calls, but Godot 4.3 can. I will just remove OffsetStep because its not necessary to the function of the signal.

**Comment by TheOathMan** [comment]
Now The [Plugin](https://github.com/TheOathMan/Godot-Android-Live-Wallpaper/releases/tag/v1.3.1) tested with 4.2.2.stable works as well.

**Comment by skeddles** [comment]
yup, after updating to that version, and removing the offsetstep parameter, it seems to be working nicely! 

Thanks so much for implementing this, it definitely opens a lot of options for us.

**Comment by skeddles** [comment]
i dont suppose there's a way to get a count of how many home screens the user has?

**Comment by TheOathMan** [comment]
Offsetstep parameter contain NumberOfHomeScreen÷1. So if x value is 0.333, that means there are 3 horizontal home screens.

The problem is, we removed that parameter because JNI breaks where there are too many parameters in 4.2.

**Comment by TheOathMan** [comment]
I'm adding a separate signal that sends home screen count

**Comment by TheOathMan** [comment]
[try](https://github.com/TheOathMan/Godot-Android-Live-Wallpaper/releases/tag/v1.3.2) the new `homescreen_count_updated(count_x:int,count_y:int)` signals. It should receive home screen count when available.

**Comment by tmape** [comment]
Thanks for sharing your awesome Live Wallpaper plugin! I'm trying to get it working on Godot, but I've hit a few issues. 

After following these steps: 

1.  Downloading and installing the Android Build Template
2.  Updating the plugin to v1.2 (it came with v1.1)
3.  Setting up the homescreen_count_updated and on_offsets_changed signals
4.  Running the project on Android via Remote Debug

I'm experiencing issues where the values don't update when changing screens, adding screen or tapping/swiping the screen. I've tried this on different Godot versions and Android devices with various Android OS versions (e.g., 8, 14), but still get the same result.

Could you help me figure out what I've done wrong? Specifically:
1.  Shouldn't the values update when adding a new screen, swiping to another screen, or tapping the screen?
2.  Am I setting up the signals incorrectly?
3.  The plugin version shown in Project Settings > Plugins doesn't seem to match the released version - have I installed it correctly?"

OS: Windows 11
Android OS: version 8 and version 11
Godot Version(Gd Script version): 4.2.2 stable.official, 4.3.stable.official

<img src="https://github.com/user-attachments/assets/402b494f-f9a6-4ead-8845-52b6a85e8f45" width="400">

<img src="https://github.com/user-attachments/assets/aaf344e3-5000-409a-ba86-a0adc7f775e7" width="400">

**Comment by TheOathMan** [comment]
try the new demo [project](https://github.com/TheOathMan/Godot-Android-Live-Wallpaper/releases/tag/V1.3.3). I have updated the plugin sdk target and fixed a previous (maybe unrelated) issue with integer rounding of home screen count. 

homescreen_count_updated signal is supposed to give you the total home screens available. So if you have 3 home screen, the signal will report 3.
the offset.x from on_offset_changed signal is a range from 0 to 1. 1 means you've scrolled horizontally to the last home screen page.

<img src="https://github.com/user-attachments/assets/5ab72ad6-8fb4-4326-bad2-7b90b09ad521" width="400">

**Comment by TheOathMan** [comment]
You are right, home screen related signals don't seem to work on Android 9, but works fine in android 14. I will see what I can find but maybe its an android sdk related issue.

**Comment by tmape** [comment]
Thanks for your prompt response! Unfortunately, I've tried installing the latest version (v1.3.3) of the Live Wallpaper plugin, but I'm still experiencing issues getting it to work. 

Specifically: 

- When installing the APK file, I don't see the debug text on the screen, despite following your instructions.
-  Using the project directly, I find that the plugin is not up-to-date and lacks the homescreen_count_updated and on_offsets_changed functions. To resolve this, I removed the existing addons folder and replaced it with the v1.3.3 version of the plugin. However, even with this update, I'm still unable to detect changes in screen count and offset.

I've tried this on Samsung S23 (OS: 14).  Could you please help me troubleshoot what's going wrong?

[GodotLiveWallpaperProject_v1.3.3.zip](https://github.com/user-attachments/files/17193915/GodotLiveWallpaperProject_v1.3.3.zip)

<img src="https://github.com/user-attachments/assets/70ad8638-e793-44b7-b895-45c56a21c812" width="400">

**Comment by TheOathMan** [comment]
Samsung's One UI launcher is known to have issues with calling the onOffsetsChanged() callback for live wallpapers. This problem has been observed in several Samsung devices across different Android versions, including older devices like the Note 8 and newer ones like the Galaxy S23. As a workaround, you can download [Pixel Launcher](https://play.google.com/store/search?q=pixel+launcher&c=apps&hl=en) which is what I'm using or [Smart Launcher 6](https://play.google.com/store/apps/details?id=ginlemon.flowerfree). These Launchers should call all home screen signals just fine. I tested the plugin in Samsung Note 8 using the default One UI Launcher, the signal don't work, but once I changed the launcher, the signal work perfectly.

Samsung heavily customizes Android, including the launcher, and these customizations can interfere with certain system callbacks like onOffsetsChanged().

To change the Launcher go to Settings>apps>(click 3 dots on top) Default apps > Home Screen:

<img src="https://github.com/user-attachments/assets/59203f06-d886-418b-9533-301b94ebc0ba" width="400">

My bad, I forgot to update the plugin files in the sample project. I did a [reupload](https://github.com/TheOathMan/Godot-Android-Live-Wallpaper/releases/tag/V1.3.3).

**Comment by tmape** [comment]
After switching to a different launcher, everything is working as expected. So, it appears that Samsung's launcher was the culprit! 

I'm grateful for your help in troubleshooting this problem. Just to confirm, I've also tested the plugin on my devices and Android versions, specifically on Samsung S7 (OS: 8) and S23 (OS: 14), with both v1.3.2 and v1.3.3 versions of the plugin, and it's working without any issues on all of them.

**Comment by TheOathMan** [comment]
I added the issue to the Known issues for future users. thanks for reporting. Good luck.
